apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
  type: LoadBalancer
  loadBalancerIP: "$(JELLYFIN_IP)" # An available IP from my MetalLB range
