apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  volumeName: jellyfin-media-pv
  storageClassName: ""  # Use empty if binding to a manually created PV

